[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "subspacead"
version = "0.1.0"
description = "SubspaceAD Codebase"
dependencies = [
    "torch",
    "torchvision",
    "transformers>=4.56.0",
    "opencv-python",
    "kornia",
    "anomalib"
]

[tool.setuptools.packages.find]
where = ["src"]
